name: agri
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  sliding_clipped_nav_bar: ^3.1.0+4


dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
