// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_zUQ2pU4E8SAFyn29N8s7vfmRCE_oG8',
    appId: '1:443778834970:web:6cf4d65aabf5049e4867a3',
    messagingSenderId: '443778834970',
    projectId: 'agri-4f707',
    authDomain: 'agri-4f707.firebaseapp.com',
    storageBucket: 'agri-4f707.appspot.com',
    measurementId: 'G-TCG66ZXWEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtrHrAyglsBr1_PBbHfBRXzYOnvQEqxFI',
    appId: '1:443778834970:android:dcb6075bbe788bd44867a3',
    messagingSenderId: '443778834970',
    projectId: 'agri-4f707',
    storageBucket: 'agri-4f707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMsobLiuHnoxH3h6bbERLxlsMw21DZC1E',
    appId: '1:443778834970:ios:defc2c37e03bc1954867a3',
    messagingSenderId: '443778834970',
    projectId: 'agri-4f707',
    storageBucket: 'agri-4f707.appspot.com',
    iosBundleId: 'com.example.verygoodcore.agri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMsobLiuHnoxH3h6bbERLxlsMw21DZC1E',
    appId: '1:443778834970:ios:89f42bdc3099e2254867a3',
    messagingSenderId: '443778834970',
    projectId: 'agri-4f707',
    storageBucket: 'agri-4f707.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
